services:
  erp-java:
    build: "."
    container_name: erp-java
    depends_on:
      erp-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - erp_backend
  erp-db:
    image: mysql:5.7
    container_name: erp-db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_pass
    ports:
      - "6033:3306"
    volumes:
      - erp_database_data:/var/lib/mysql
    networks:
      - erp_backend
  erp-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: erp-pma
    links:
      - erp-db
    environment:
      PMA_HOST: erp-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - erp_backend
volumes:
  erp_database_data:

networks:
  erp_backend:

